// GENERATED FILE - do not edit directly.
// Source: src/lib/transform-core.ts. Regenerate with: npm run build:script
//
// Deploy: open https://www.office.com -> Excel -> open NoteSync/runner.xlsx ->
// Automate tab -> New Script -> replace the editor contents with this entire
// file -> rename the script to "NoteSync Transform" -> Save script.

// Core transcript -> OneNote page HTML transformation.
//
// This file is the source of truth for office-script/transform.ts, which is
// generated by `npm run build:script` and pasted into the M365 Office Scripts
// editor. Because of that it must stay self-contained: no imports, no Node
// APIs, only language features supported by the Office Scripts runtime.

interface TranscriptTurn {
  speaker: string;
  startSeconds: number;
  text: string;
}

interface InsightNote {
  title: string;
  text: string;
  subpoints: { title: string; text: string }[];
}

interface ActionItem {
  owner: string;
  text: string;
}

// --- VTT parsing ---------------------------------------------------------

function parseTimestamp(ts: string): number {
  // Accepts hh:mm:ss.ttt or mm:ss.ttt
  const parts = ts.split(":");
  let h = 0;
  let m = 0;
  let s = "0";
  if (parts.length === 3) {
    h = Number(parts[0]);
    m = Number(parts[1]);
    s = parts[2] || "0";
  } else if (parts.length === 2) {
    m = Number(parts[0]);
    s = parts[1] || "0";
  }
  const sec = Number(s.split(".")[0]);
  if (isNaN(h) || isNaN(m) || isNaN(sec)) {
    return 0;
  }
  return h * 3600 + m * 60 + sec;
}

function decodeEntities(value: string): string {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const mm = h > 0 && m < 10 ? "0" + m : String(m);
  const ss = s < 10 ? "0" + s : String(s);
  return h > 0 ? h + ":" + mm + ":" + ss : mm + ":" + ss;
}

/**
 * Parses a Teams WEBVTT transcript into speaker turns, merging consecutive
 * cues from the same speaker. Teams cues look like:
 *
 *   a39a3a06-.../12-0
 *   00:00:03.120 --> 00:00:05.520
 *   <v Venkat Yenduri>Hello everyone.</v>
 */
function parseVtt(vtt: string): TranscriptTurn[] {
  const lines = vtt.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
  const cues: TranscriptTurn[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = (lines[i] || "").trim();
    if (line.indexOf("-->") === -1) {
      i++;
      continue;
    }
    const start = parseTimestamp(line.split("-->")[0]!.trim());
    i++;
    const textLines: string[] = [];
    while (i < lines.length && (lines[i] || "").trim() !== "") {
      textLines.push((lines[i] || "").trim());
      i++;
    }
    const raw = textLines.join(" ");
    const spanRe = /<v(?:\.[^\s>]+)*\s+([^>]+)>(.*?)<\/v>/g;
    let matched = false;
    let m = spanRe.exec(raw);
    while (m !== null) {
      matched = true;
      const text = decodeEntities(m[2]!.trim());
      if (text) {
        cues.push({ speaker: decodeEntities(m[1]!.trim()), startSeconds: start, text: text });
      }
      m = spanRe.exec(raw);
    }
    if (!matched) {
      // Voice span without a closing tag (some producers omit it).
      const open = raw.match(/<v(?:\.[^\s>]+)*\s+([^>]+)>(.*)$/);
      if (open) {
        const text = decodeEntities(open[2]!.replace(/<[^>]*>/g, "").trim());
        if (text) {
          cues.push({ speaker: decodeEntities(open[1]!.trim()), startSeconds: start, text: text });
        }
      } else {
        const text = decodeEntities(raw.replace(/<[^>]*>/g, "").trim());
        if (text) {
          cues.push({ speaker: "", startSeconds: start, text: text });
        }
      }
    }
  }

  const turns: TranscriptTurn[] = [];
  for (const cue of cues) {
    const last = turns.length > 0 ? turns[turns.length - 1] : undefined;
    if (last && last.speaker === cue.speaker) {
      last.text += " " + cue.text;
    } else {
      turns.push({ speaker: cue.speaker, startSeconds: cue.startSeconds, text: cue.text });
    }
  }
  return turns;
}

// --- AI insight parsing ---------------------------------------------------

function asString(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function parseJsonArray(json: string): unknown[] {
  if (!json) {
    return [];
  }
  try {
    const parsed: unknown = JSON.parse(json);
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    return [];
  }
}

/**
 * Normalizes the Graph aiInsight meetingNotes payload. Items are expected to
 * be { title, text, subpoints: [{ title, text }] } but plain strings and
 * partial objects are tolerated.
 */
function parseInsightNotes(notesJson: string): InsightNote[] {
  const notes: InsightNote[] = [];
  for (const item of parseJsonArray(notesJson)) {
    if (typeof item === "string") {
      if (item.trim()) {
        notes.push({ title: "", text: item.trim(), subpoints: [] });
      }
      continue;
    }
    if (typeof item !== "object" || item === null) {
      continue;
    }
    const obj = item as { [key: string]: unknown };
    const subpoints: { title: string; text: string }[] = [];
    if (Array.isArray(obj.subpoints)) {
      for (const sub of obj.subpoints) {
        if (typeof sub === "object" && sub !== null) {
          const subObj = sub as { [key: string]: unknown };
          const subTitle = asString(subObj.title);
          const subText = asString(subObj.text);
          if (subTitle || subText) {
            subpoints.push({ title: subTitle, text: subText });
          }
        }
      }
    }
    const title = asString(obj.title);
    const text = asString(obj.text);
    if (title || text || subpoints.length > 0) {
      notes.push({ title: title, text: text, subpoints: subpoints });
    }
  }
  return notes;
}

/** Normalizes the Graph aiInsight actionItems payload. */
function parseActionItems(actionItemsJson: string): ActionItem[] {
  const items: ActionItem[] = [];
  for (const item of parseJsonArray(actionItemsJson)) {
    if (typeof item === "string") {
      if (item.trim()) {
        items.push({ owner: "", text: item.trim() });
      }
      continue;
    }
    if (typeof item !== "object" || item === null) {
      continue;
    }
    const obj = item as { [key: string]: unknown };
    const text = asString(obj.text) || asString(obj.title);
    const owner = asString(obj.ownerDisplayName) || asString(obj.owner);
    if (text) {
      items.push({ owner: owner, text: text });
    }
  }
  return items;
}

// --- HTML building --------------------------------------------------------
// OneNote's "Create page in a section" renders whitespace between tags as
// literal text, so all HTML below is concatenated with no newlines or
// indentation.

function buildSummaryHtml(notes: InsightNote[], actionItems: ActionItem[]): string {
  let html = "<h1>Summary</h1>";
  if (notes.length === 0 && actionItems.length === 0) {
    html += "<p><i>No AI summary was available for this meeting. " +
      "Summaries require Copilot to be active and transcription enabled.</i></p>";
    return html;
  }
  if (notes.length > 0) {
    html += "<ul>";
    for (const note of notes) {
      html += "<li>";
      if (note.title) {
        html += "<b>" + escapeHtml(note.title) + "</b>";
        if (note.text) {
          html += ": ";
        }
      }
      html += escapeHtml(note.text);
      if (note.subpoints.length > 0) {
        html += "<ul>";
        for (const sub of note.subpoints) {
          html += "<li>";
          if (sub.title) {
            html += "<b>" + escapeHtml(sub.title) + "</b>";
            if (sub.text) {
              html += ": ";
            }
          }
          html += escapeHtml(sub.text) + "</li>";
        }
        html += "</ul>";
      }
      html += "</li>";
    }
    html += "</ul>";
  }
  if (actionItems.length > 0) {
    html += "<h2>Action Items</h2><ul>";
    for (const item of actionItems) {
      html += "<li>";
      if (item.owner) {
        html += "<b>" + escapeHtml(item.owner) + ":</b> ";
      }
      html += escapeHtml(item.text) + "</li>";
    }
    html += "</ul>";
  }
  return html;
}

function buildTranscriptHtml(turns: TranscriptTurn[]): string {
  let html = "<h1>Transcript</h1>";
  if (turns.length === 0) {
    html += "<p><i>The transcript was empty.</i></p>";
    return html;
  }
  for (const turn of turns) {
    const speaker = turn.speaker ? escapeHtml(turn.speaker) : "Unknown speaker";
    html += "<p><b>" + speaker + "</b> [" + formatTimestamp(turn.startSeconds) + "] " +
      escapeHtml(turn.text) + "</p>";
  }
  return html;
}

/**
 * Builds the complete OneNote page HTML.
 *
 * @param vtt Raw WEBVTT transcript content.
 * @param subject Meeting subject, e.g. "Weekly Sync".
 * @param dateStr Meeting date already formatted as yyyy-MM-dd (local time).
 * @param notesJson JSON array string of aiInsight meetingNotes ("" or "[]" when absent).
 * @param actionItemsJson JSON array string of aiInsight actionItems ("" or "[]" when absent).
 */
function buildPageHtml(
  vtt: string,
  subject: string,
  dateStr: string,
  notesJson: string,
  actionItemsJson: string
): string {
  const title = dateStr + " - " + subject;
  const notes = parseInsightNotes(notesJson);
  const actionItems = parseActionItems(actionItemsJson);
  const turns = parseVtt(vtt);
  return "<html><head><title>" + escapeHtml(title) + "</title></head><body>" +
    buildSummaryHtml(notes, actionItems) +
    "<hr/>" +
    buildTranscriptHtml(turns) +
    "</body></html>";
}

/**
 * Entry point invoked by Power Automate (Excel Online "Run script" action).
 * The workbook is unused; it exists only because Office Scripts require one.
 *
 * Parameter order must match the "Run script" action configuration:
 * vtt, subject, dateStr, notesJson, actionItemsJson.
 */
function main(
  workbook: ExcelScript.Workbook,
  vtt: string,
  subject: string,
  dateStr: string,
  notesJson: string,
  actionItemsJson: string
): string {
  return buildPageHtml(vtt, subject, dateStr, notesJson, actionItemsJson);
}
